/**
 * Expo config plugin: wire a release signing config into the generated Android project.
 *
 * Why this exists: `android/` is gitignored (see .gitignore) and regenerated by
 * `expo prebuild` on every CI run, so a hand-edited `android/app/build.gradle`
 * would be thrown away. The bare-minimum template ships only a `debug`
 * signingConfig and points `buildTypes.release` at it, which is why Google Play
 * rejected the upload with "APK has been signed in debug mode".
 *
 * This plugin re-applies the fix after every prebuild:
 *   1. adds a `release` signingConfig that reads Codemagic's CM_KEYSTORE_* vars
 *   2. repoints `buildTypes.release` from signingConfigs.debug to .release
 *
 * No secrets live here. The keystore and its passwords come from Codemagic's
 * encrypted code-signing store at build time.
 */
const { withAppBuildGradle } = require('expo/config-plugins');

const RELEASE_SIGNING_CONFIG = `
        release {
            storeFile file(System.getenv("CM_KEYSTORE_PATH") ?: "release.keystore")
            storePassword System.getenv("CM_KEYSTORE_PASSWORD")
            keyAlias System.getenv("CM_KEY_ALIAS")
            keyPassword System.getenv("CM_KEY_PASSWORD")
        }`;

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withAndroidReleaseSigning: expected a Groovy build.gradle, got "${cfg.modResults.language}"`
      );
    }

    let gradle = cfg.modResults.contents;

    // 1. Declare the release signingConfig alongside the template's debug one.
    if (!gradle.includes('CM_KEYSTORE_PATH')) {
      if (!/signingConfigs \{\n/.test(gradle)) {
        throw new Error('withAndroidReleaseSigning: signingConfigs block not found');
      }
      gradle = gradle.replace(/(signingConfigs \{\n)/, `$1${RELEASE_SIGNING_CONFIG}\n`);
    }

    // 2. Point buildTypes.release at it. Slice at `buildTypes {` first, so the
    //    debug signingConfig declared above it can never be rewritten.
    const buildTypesAt = gradle.indexOf('buildTypes {');
    if (buildTypesAt === -1) {
      throw new Error('withAndroidReleaseSigning: buildTypes block not found');
    }

    gradle =
      gradle.slice(0, buildTypesAt) +
      gradle
        .slice(buildTypesAt)
        .replace(
          /release \{([\s\S]*?)signingConfig signingConfigs\.debug/,
          'release {$1signingConfig signingConfigs.release'
        );

    // Fail the build loudly rather than shipping another debug-signed artifact.
    if (!gradle.includes('signingConfig signingConfigs.release')) {
      throw new Error(
        'withAndroidReleaseSigning: could not repoint buildTypes.release — ' +
          'the Expo template may have changed. Inspect android/app/build.gradle.'
      );
    }

    cfg.modResults.contents = gradle;
    return cfg;
  });
};
